// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Persistent.SqlServer.DbContexts;

#nullable disable

namespace NotificationService.Persistent.SqlServer.Migrations
{
    [DbContext(typeof(NotificationServiceMssqlDbContext))]
    partial class NotificationServiceMssqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Entity.NotificationMessageQueue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BccTargets")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CcTargets")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DeliveryTarget")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("EnqueuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastAttemptException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("NeedSendImmediately")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationTypeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("PlanToSendAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("SenderEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("NotificationMessageQueue", "NotificationService");
                });
#pragma warning restore 612, 618
        }
    }
}
