namespace WebApi.GenericCRUD.Generator.Utils;

internal static class FileTemplates
{
    public static string GetFileHeader(string className)
    {
        return $@"/****************************************************

 -----------------------------------------------------------------------
|          DotNet Brightener Auto CRUD Web API Generator Tool           |
|                               ---o0o---                               |
 -----------------------------------------------------------------------

This file is generated by an automation tool and it could be re-generated every time
you build the project.

Don't change this file as your changes will be lost when the file is re-generated.
If you need to change the content for this entity, update the {className}.cs file
which should be in the same folder as this file.

© {DateTime.Now.Year} DotNet Brightener. <admin@dotnetbrightener.com>

****************************************************/";
    }
}

internal static class FilePathHelper
{
    internal static string GetAssemblyPath(this string lookingPath)
    {
        var expectingAssemblyDirectory = Path.GetDirectoryName(lookingPath);

        while (true)
        {
            var files = Directory.GetFiles(expectingAssemblyDirectory, "*.csproj");

            if (files.Count() == 1)
            {
                return expectingAssemblyDirectory;
            }

            expectingAssemblyDirectory = Directory.GetParent(expectingAssemblyDirectory)?.FullName;
        }

        return null;
    }
}