// <auto-generated />
using System;
using DotNetBrightener.Integration.DataMigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetBrightener.Integration.DataMigration.Migrations
{
    [DbContext(typeof(DataMigrationMsSQLDbContext))]
    [Migration("20201203045000_InitializeDataMigrationSchema")]
    partial class InitializeDataMigrationSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DotNetBrightener.Integration.DataMigration.DataMigrationHistoryRecord", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("MigrationRecorded")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MigrationId");

                    b.ToTable("__DataMigrationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
