// <auto-generated />
using System;
using ActivityLog.DataStorage.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActivityLog.DataStorage.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerMigrationDbContext))]
    [Migration("20250929021522_Add_TenantId_Column_To_ActivityLogTable")]
    partial class Add_TenantId_Column_To_ActivityLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityLog.Entities.ActivityLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClassName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("ExecutionDurationMs")
                        .HasColumnType("float");

                    b.Property<string>("InputParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MethodName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReturnValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Tags")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TargetEntity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetEntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClassName")
                        .HasDatabaseName("IX_ActivityLog_ClassName");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_ActivityLog_CorrelationId");

                    b.HasIndex("IsSuccess")
                        .HasDatabaseName("IX_ActivityLog_IsSuccess");

                    b.HasIndex("LogLevel")
                        .HasDatabaseName("IX_ActivityLog_LogLevel");

                    b.HasIndex("MethodName")
                        .HasDatabaseName("IX_ActivityLog_MethodName");

                    b.HasIndex("Namespace")
                        .HasDatabaseName("IX_ActivityLog_Namespace");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_ActivityLog_StartTime");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ActivityLog_UserId");

                    b.HasIndex("StartTime", "IsSuccess")
                        .HasDatabaseName("IX_ActivityLog_StartTime_IsSuccess");

                    b.HasIndex("Namespace", "ClassName", "StartTime")
                        .HasDatabaseName("IX_ActivityLog_Namespace_ClassName_StartTime");

                    b.ToTable("ActivityLogRecord", "ActivityLog");
                });
#pragma warning restore 612, 618
        }
    }
}
