// <auto-generated />
using System;
using DotNetBrightener.Infrastructure.AppClientManager.DataStorage.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetBrightener.Infrastructure.AppClientManager.DataStorage.PostgreSql.Migrations
{
    [DbContext(typeof(MigrationPostgreSqlDbContext))]
    [Migration("20240504043013_Init_AppClient_Tables_Schema")]
    partial class Init_AppClient_Tables_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetBrightener.DataAccess.EF.Entities.EnumLookupEntity<DotNetBrightener.Infrastructure.AppClientManager.Models.AppClientStatus>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("AppClientStatusValue");

                    b.HasKey("Id");

                    b.ToTable("AppClientStatusLookup", "AppClient");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Value = "Inactive"
                        },
                        new
                        {
                            Id = 30,
                            Value = "Active"
                        },
                        new
                        {
                            Id = 50,
                            Value = "Suspended"
                        });
                });

            modelBuilder.Entity("DotNetBrightener.DataAccess.EF.Entities.EnumLookupEntity<DotNetBrightener.Infrastructure.AppClientManager.Models.AppClientType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("AppClientTypeValue");

                    b.HasKey("Id");

                    b.ToTable("AppClientTypeLookup", "AppClient");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Value = "NoRestriction"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Web"
                        },
                        new
                        {
                            Id = 10,
                            Value = "Mobile"
                        },
                        new
                        {
                            Id = 20,
                            Value = "Desktop"
                        });
                });

            modelBuilder.Entity("DotNetBrightener.Infrastructure.AppClientManager.Models.AppClient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedAppBundleIds")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("AllowedOrigins")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecretHashed")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ClientSecretSalt")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("ClientStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ClientType")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeactivatedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AllowedOrigins");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("AppClient", "AppClient");
                });

            modelBuilder.Entity("DotNetBrightener.Infrastructure.AppClientManager.Models.AppClientAccessScope", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Destination")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Scope")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AppClientId");

                    b.ToTable("AppClientAccessScope", "AppClient");
                });

            modelBuilder.Entity("DotNetBrightener.Infrastructure.AppClientManager.Models.AppClientAccessScope", b =>
                {
                    b.HasOne("DotNetBrightener.Infrastructure.AppClientManager.Models.AppClient", "AppClient")
                        .WithMany()
                        .HasForeignKey("AppClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppClient");
                });
#pragma warning restore 612, 618
        }
    }
}
