using CRUD_With_gRPC.Core;
using CRUD_With_gRPC.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services
       .AddGrpc()
       .AddJsonTranscoding();

builder.Services.AddScoped<IProductGrpcService, ProductGrpcService>();

var app = builder.Build();

app.UseRouting();
app.UseGrpcWeb(new GrpcWebOptions { DefaultEnabled = true });

// Configure the HTTP request pipeline.


#region gRPC service registration
/****************************************************
 -----------------------------------------------------------------------
|          DotNet Brightener gRPC Service Generator Tool                |
|                               ---o0o---                               |
 -----------------------------------------------------------------------

This file is generated by an automation tool and it could be re-generated every time
you build the project.

Don't change this section as your changes will be messed up when the section get re-generated.

© 2024 DotNet Brightener. <admin@dotnetbrightener.com>

****************************************************/



app.MapGrpcService<ProductServiceImpl>();
          

#endregion gRPC service registration

app.MapGrpcService<GreeterService>();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();
