// <auto-generated />
using System;
using DotNetBrightener.Core.Logging.PostgreSqlDbStorage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetBrightener.Core.Logging.PostgreSqlDbStorage.Migrations
{
    [DbContext(typeof(LoggingDbContext))]
    partial class LoggingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetBrightener.Core.Logging.EventLog", b =>
                {
                    b.Property<string>("FormattedMessage")
                        .HasColumnType("text");

                    b.Property<string>("FullMessage")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("LoggerName")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("PropertiesDictionary")
                        .HasColumnType("text");

                    b.Property<string>("RemoteIpAddress")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<string>("RequestUrl")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("TenantIds")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasIndex("Level");

                    b.HasIndex("LoggerName");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("LoggerName"), new[] { "Level", "TimeStamp" });

                    b.HasIndex("RequestId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RequestId"), new[] { "TimeStamp", "Level" });

                    b.HasIndex("TimeStamp");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("TimeStamp"), new[] { "Level", "LoggerName" });

                    b.ToTable("EventLog", "Log");
                });
#pragma warning restore 612, 618
        }
    }
}
