namespace DotNetBrightener.OAuth.Integration.Apple.Models;

/// <summary>
///Object containing information about the user. 
/// </summary>
public class AppleUserInformation
{
    /// <summary>
    /// Unique ID generated by Apple for your app.
    /// </summary>
    public string UserID { get; set; }
    /// <summary>
    /// Email address of the user.
    /// </summary>
    public string Email { get; set; }
    /// <summary>
    /// Boolean value displaying if the user has verified email address.
    /// </summary>
    public string EmailVerified { get; set; }
    /// <summary>
    /// UTC date and time of authentication.
    /// </summary>
    public DateTime TimeOfAuthentication { get; set; }
}


public class AppleUserInfoModel
{
    public AppleNameInfoObject Name { get; set; }
    public string Email { get; set; }
}

public class AppleNameInfoObject
{
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
}


public class AppleNameInfoClientObject
{
    public string GivenName { get; set; }
    public string FamilyName { get; set; }
    public string MiddleName { get; set; }
}

