name: push_notification_test
description: A Flutter app for testing DotNetBrightener Push Notification library

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.2
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Local notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  # App icons
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icon/icon.png"
