trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /src/*
    exclude:
      - version.json
      - Pipelines/*
      - '**/README.md'

pool:
  vmImage:
    "ubuntu-latest"

    # pool:
    #   name: dotnetbrightener-selfhosted
    #   demands:
    #   - agent.name -equals self-hosted

variables:
- group: dotnet-brightener

- name: projectName
  value: 'DotNetBrightenerFramework'

- name: projectFolder
  value: 'src'

- name: buildConfiguration
  value: Release

parameters:
  - name: versionIncrementType
    displayName: Version Increment Type
    type: string
    default: Preview Version
    values:
      - Major Feature
      - Feature
      - BugFix
      - Preview Version

stages:
  - template: ReleaseNewPackageVersionTemplate.yml
    parameters:
      projectFolder: $(projectFolder)
      projectName: $(projectName)
      versionIncrementType: ${{ parameters.versionIncrementType }}
