using DotNetBrightener.gRPC.Generator.Templates;
using System.IO;

namespace DotNetBrightener.gRPC.Generator.Generators;

public partial class ProtoFileGenerator
{
    private static string GenerateProtoFile(string targetFolder, ProtoFileDefinition modelClass)
    {
        var className = $"{modelClass.ServiceName}";

        if (!Directory.Exists(targetFolder))
        {
            Directory.CreateDirectory(targetFolder);
        }

        var defaultPathFile = Path.Combine(targetFolder, $"{className}.proto");

        var fileContent = ProtoFileTemplate.Generate(modelClass);

        var defaultProtoFileContent = $@"
// <auto-generated>
//     Generated by the protocol buffer generator.  DO NOT EDIT!
// </auto-generated>

{fileContent}
";
        File.WriteAllText(defaultPathFile, defaultProtoFileContent);

        return className;
    }
}