using System.IO;
using DotNetBrightener.WebApi.GenericCRUD.Generator.SyntaxReceivers;
using DotNetBrightener.WebApi.GenericCRUD.Generator.Utils;
using Microsoft.CodeAnalysis;

namespace DotNetBrightener.WebApi.GenericCRUD.Generator.Generators;

[Generator]
public class DataServiceClassGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new AutoGenerateDataServiceSyntaxReceiver());
    }

    /// <summary>
    /// And consume the receiver here.
    /// </summary>
    public void Execute(GeneratorExecutionContext context)
    {
        var models = (context.SyntaxContextReceiver as AutoGenerateDataServiceSyntaxReceiver).Models;

        foreach (var modelClass in models)
        {
            var className = $"{modelClass.TargetEntity}DataService";

            var dataServiceSrc = $@"
{FileTemplates.GetFileHeader(className)}

using System;
using System.ComponentModel.DataAnnotations;

using DotNetBrightener;
using DotNetBrightener.DataAccess.Services;
using {modelClass.TargetEntityNamespace};

namespace {modelClass.DataServiceNamespace};

public partial interface I{modelClass.TargetEntity}DataService : IBaseDataService<{modelClass.TargetEntity}> {{ }}

public partial class {modelClass.TargetEntity}DataService : BaseDataService<{modelClass.TargetEntity}>, I{modelClass.TargetEntity}DataService {{
    
    internal {modelClass.TargetEntity}DataService(IRepository repository)
        : base(repository)
    {{
    }}

}}";


        var targetFolder = modelClass.DataServicePath;

            if (!Directory.Exists(targetFolder))
            {
                Directory.CreateDirectory(targetFolder);
            }

            var gPathFile = Path.Combine(targetFolder, $"{className}.g.cs");

            File.WriteAllText(gPathFile, dataServiceSrc);

            var defaultPathFile = Path.Combine(targetFolder, $"{className}.cs");

            if (!File.Exists(defaultPathFile))
            {
                var defaultServiceClassFileContent = $@"
using DotNetBrightener.DataAccess.Services;
using Microsoft.Extensions.Logging;

using {modelClass.TargetEntityNamespace};

namespace {modelClass.DataServiceNamespace};

/// <summary>
///     Provides the data access methods for <see cref=""{modelClass.TargetEntity}"" /> entity.
/// </summary>
public partial interface I{modelClass.TargetEntity}DataService 
{{
    // Provide your custom methods here
}}

public partial class {modelClass.TargetEntity}DataService
{{
    private readonly ILogger _logger;

    public {modelClass.TargetEntity}DataService(
            IRepository repository, 
            ILogger<{modelClass.TargetEntity}DataService> logger)
        : this(repository)
    {{
        _logger = logger;
    }}

    // Implement your custom methods here
}}";
                File.WriteAllText(defaultPathFile, defaultServiceClassFileContent);
            }
        }
    }
}