using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using WebApi.GenericCRUD.Generator.Utils;

namespace WebApi.GenericCRUD.Generator.SyntaxReceivers;

public static class AutoGenerateDataServiceSyntaxReceiver
{
    // Static method for IIncrementalGenerator predicate
    public static bool IsCandidateForGeneration(SyntaxNode node, CancellationToken cancellationToken)
    {
        // Check if this is a class declaration
        if (node is not ClassDeclarationSyntax classDec)
        {
            return false;
        }

        // Check if this class implements ICRUDDataServiceGeneratorRegistration interface
        return classDec.BaseList?.Types.Any(baseType =>
        {
            var typeName = baseType.Type.ToString();
            return typeName == "ICRUDDataServiceGeneratorRegistration" ||
                   typeName.EndsWith(".ICRUDDataServiceGeneratorRegistration");
        }) == true;
    }

    // Static method for IIncrementalGenerator transform
    public static IEnumerable<CodeGenerationInfo> GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        //if (!Debugger.IsAttached)
        //{
        //    Debugger.Launch();
        //}

        var classDec      = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var classSymbol   = semanticModel.GetDeclaredSymbol(classDec);

        if (classSymbol == null)
        {
            return null;
        }

        // Validate that the class actually implements ICRUDDataServiceGeneratorRegistration interface
        if (classSymbol is INamedTypeSymbol namedTypeSymbol)
        {
            var implementsInterface = namedTypeSymbol.AllInterfaces.Any(i =>
                i.Name == "ICRUDDataServiceGeneratorRegistration" ||
                i.ToDisplayString().EndsWith(".ICRUDDataServiceGeneratorRegistration"));

            if (!implementsInterface)
            {
                return null;
            }
        }
        else
        {
            return null;
        }

        var    containingAssembly = classSymbol.ContainingAssembly;
        string assemblyDirectory  = "";

        if (containingAssembly != null)
        {
            var assemblyPath = containingAssembly.Locations.FirstOrDefault()?.SourceTree?.FilePath;

            if (!string.IsNullOrEmpty(assemblyPath))
            {
                assemblyDirectory = assemblyPath.GetAssemblyPath();
            }
        }

        if (string.IsNullOrEmpty(assemblyDirectory))
            return null;

        var compilation           = semanticModel.Compilation;
        var generatedAssemblyName = compilation.AssemblyName;

        var members = classDec.Members;

        List<CodeGenerationInfo> modelsList = [];

        // Look for both fields and properties with the name "Entities"
        foreach (var memberDeclarationSyntax in members.OfType<FieldDeclarationSyntax>())
        {
            var typeInfo = semanticModel.GetTypeInfo(memberDeclarationSyntax.Declaration.Type);

            if (memberDeclarationSyntax.Declaration.Variables.FirstOrDefault()?.Initializer == null)
            {
                continue;
            }

            var valueInitializer = memberDeclarationSyntax.Declaration
                                                          .Variables
                                                          .First()
                                                          .Initializer;

            if (valueInitializer is null)
                continue;

            if (typeInfo.Type?.ToString() == "System.Collections.Generic.List<System.Type>")
            {
                // Handle InitializerExpressionSyntax (older C# versions)
                if (valueInitializer.Value is InitializerExpressionSyntax initExpr)
                {
                    foreach (var expr in initExpr.Expressions)
                    {
                        if (expr is TypeOfExpressionSyntax typeOfExpr)
                        {
                            var extractedType = semanticModel.GetTypeInfo(typeOfExpr.Type).Type;

                            if (extractedType is ITypeSymbol typeS &&
                                typeS.ContainingNamespace.ToDisplayString() != "<global namespace>")
                            {
                                modelsList.Add(new CodeGenerationInfo
                                {
                                    TargetEntity          = typeS.Name,
                                    TargetEntityNamespace = typeS.ContainingNamespace.ToDisplayString(),
                                    DataServiceNamespace  = $"{generatedAssemblyName}.Data",
                                    DataServicePath       = Path.Combine(assemblyDirectory, "Data"),
                                    DataServiceAssembly   = generatedAssemblyName
                                });
                            }
                        }
                    }
                }
                // Handle CollectionExpressionSyntax (C# 12+)
                else if (valueInitializer.Value is CollectionExpressionSyntax collExpr)
                {
                    foreach (var element in collExpr.Elements.OfType<ExpressionElementSyntax>())
                    {
                        if (element.Expression is TypeOfExpressionSyntax typeOfExpr)
                        {
                            var extractedType = semanticModel.GetTypeInfo(typeOfExpr.Type).Type;

                            if (extractedType is ITypeSymbol typeS &&
                                typeS.ContainingNamespace.ToDisplayString() != "<global namespace>")
                            {
                                modelsList.Add(new CodeGenerationInfo
                                {
                                    TargetEntity          = typeS.Name,
                                    TargetEntityNamespace = typeS.ContainingNamespace.ToDisplayString(),
                                    DataServiceNamespace  = $"{generatedAssemblyName}.Data",
                                    DataServicePath       = Path.Combine(assemblyDirectory, "Data"),
                                    DataServiceAssembly   = generatedAssemblyName
                                });
                            }
                        }
                    }
                }
            }
        }

        // Also look for properties with the name "Entities"
        foreach (var propertyDeclarationSyntax in members.OfType<PropertyDeclarationSyntax>())
        {
            if (propertyDeclarationSyntax.Identifier.ToString() != "Entities")
                continue;

            var typeInfo = semanticModel.GetTypeInfo(propertyDeclarationSyntax.Type);

            if (propertyDeclarationSyntax.Initializer?.Value == null)
                continue;

            var valueInitializer = propertyDeclarationSyntax.Initializer;

            if (typeInfo.Type?.ToString() == "System.Collections.Generic.List<System.Type>")
            {
                // Handle InitializerExpressionSyntax (older C# versions)
                if (valueInitializer.Value is InitializerExpressionSyntax initExpr)
                {
                    foreach (var expr in initExpr.Expressions)
                    {
                        if (expr is TypeOfExpressionSyntax typeOfExpr)
                        {
                            var extractedType = semanticModel.GetTypeInfo(typeOfExpr.Type).Type;

                            if (extractedType is ITypeSymbol typeS &&
                                typeS.ContainingNamespace.ToDisplayString() != "<global namespace>")
                            {
                                modelsList.Add(new CodeGenerationInfo
                                {
                                    TargetEntity          = typeS.Name,
                                    TargetEntityNamespace = typeS.ContainingNamespace.ToDisplayString(),
                                    DataServiceNamespace  = $"{generatedAssemblyName}.Data",
                                    DataServicePath       = Path.Combine(assemblyDirectory, "Data"),
                                    DataServiceAssembly   = generatedAssemblyName
                                });
                            }
                        }
                    }
                }
                // Handle CollectionExpressionSyntax (C# 12+)
                else if (valueInitializer.Value is CollectionExpressionSyntax collExpr)
                {
                    foreach (var element in collExpr.Elements.OfType<ExpressionElementSyntax>())
                    {
                        if (element.Expression is TypeOfExpressionSyntax typeOfExpr)
                        {
                            var extractedType = semanticModel.GetTypeInfo(typeOfExpr.Type).Type;

                            if (extractedType is ITypeSymbol typeS &&
                                typeS.ContainingNamespace.ToDisplayString() != "<global namespace>")
                            {
                                modelsList.Add(new CodeGenerationInfo
                                {
                                    TargetEntity          = typeS.Name,
                                    TargetEntityNamespace = typeS.ContainingNamespace.ToDisplayString(),
                                    DataServiceNamespace  = $"{generatedAssemblyName}.Data",
                                    DataServicePath       = Path.Combine(assemblyDirectory, "Data"),
                                    DataServiceAssembly   = generatedAssemblyName
                                });
                            }
                        }
                    }
                }
            }
        }

        return modelsList;
    }
}
