
/****************************************************

 -----------------------------------------------------------------------
|          DotNet Brightener Auto CRUD Web API Generator Tool           |
|                               ---o0o---                               |
 -----------------------------------------------------------------------

This file is generated by an automation tool and it could be re-generated every time
you build the project.

Don't change this file as your changes will be lost when the file is re-generated.
If you need to change the content for this entity, update the ProductDocumentController.cs file
which should be in the same folder as this file.

© 2024 DotNet Brightener. <admin@dotnetbrightener.com>

****************************************************/

using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using DotNetBrightener.WebApi.GenericCRUD.Controllers;
using DotNetBrightener.DataAccess.Services;
using CRUDWebApiWithGeneratorDemo.Services.Data;
using CRUDWebApiWithGeneratorDemo.Core.Entities;

/****************************************************

This partial class is added with customized document comments that are fit for the linked type ProductDocument.

Any overriden logic should be done in the other part of the file, ProductDocumentController.cs.

****************************************************/

namespace CRUDWebApiWithGeneratorDemo.Controllers;

public partial class ProductDocumentController
{
    
    internal ProductDocumentController(
        IProductDocumentDataService dataService)
        : base(dataService)
    {
    }


    /// <summary>
    ///     Retrieves the collection of records of type <see cref="ProductDocument" />.
    /// </summary>
    /// <response code="200">
    ///     The collection of records of type <see cref="ProductDocument" />.
    /// </response>
    /// <response code="401">
    ///     Unauthorized request to retrieve filtered collection of <see cref="ProductDocument" /> records.
    /// </response> 
    /// <response code="500">
    ///     Unknown internal server error.
    /// </response>
    [ProducesResponseType<List<ProductDocument>>(200)]
    public override partial Task<IActionResult> GetList();
}