variables:
- group: dotnet-brightener
- name: BuildParameters.RestoreBuildProjects
  value: 'src/DotNetBrightenerFramework.sln'

- name: BuildConfiguration
  value: Release

- name: ExtractedBuildNo
  value: $[replace(replace(replace(variables['System.PullRequest.targetBranchName'], 'releases/', ''), 'preview/', ''), 'refs/heads/', '')]

name: $(ExtractedBuildNo)

trigger: none 

jobs:
- job: Test
  displayName: Test Packages

  pool:
    vmImage: 'ubuntu-latest'

  # pool:
  #   name: dotnetbrightener-selfhosted
  #   demands: 
  #   - agent.name -equals self-hosted

  steps:
  - checkout: self
    displayName: Checking out $(Build.BuildNumber)
    submodules: true
    persistCredentials: true

  - task: UseDotNet@2
    displayName: Ensure .NET Core SDK Installed
    inputs:
      version: 8.x
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: Restore Packages
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: -p:GeneratePackageOnBuild=false --configuration $(BuildConfiguration)

- job: Build_Packages
  displayName: Building packages

  pool:
    vmImage: 'ubuntu-latest'

  # pool:
  #   name: dotnetbrightener-selfhosted
  #   demands: 
  #   - agent.name -equals self-hosted

  steps:
  - checkout: self
    displayName: Checking out $(Build.BuildNumber)
    submodules: true
    persistCredentials: true

  - task: UseDotNet@2
    displayName: Ensure .NET Core SDK Installed
    inputs:
      version: 8.x
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: Restore Packages
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)

  - task: DotNetCoreCLI@2
    displayName: Building version $(Build.BuildNumber)
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) -p:Version=$(Build.BuildNumber)
  
  - task: PublishBuildArtifacts@1
    displayName: "Archiving Artifact"
    inputs:
      PathtoPublish: 'src/nupkg_release'
      ArtifactName: 'dnb-framework'
      publishLocation: 'Container'

- job: Mirror_To_Github
  displayName: Mirror to Github

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        git clone --bare "https://justinchasez04121990:$(AzureAccessToken)@dev.azure.com/justinchasez/DotNet%20Brightener/_git/dotnet-brightener-framework"
        cd dotnet-brightener-framework.git
        git push --mirror https://$(GithubAccessToken)@github.com/DotNetBrightener/dotnet-brightener-framework
        cd ..
        rm -Rf dotnet-brightener-framework.git
    displayName: 'Mirror to Github'