variables:
- name: BuildParameters.RestoreBuildProjects
  value: 'src/DotNetBrightenerFramework.sln'
- name: BuildConfiguration
  value: Release
name: $(date:yyyyMMdd)$(rev:.r)
trigger: none 
pr:
  branches:
    include:
    - master
jobs:
- job: Building_Release
  displayName: Running on self-hosted agent
  pool:
    name: dotnetbrightener-selfhosted
    demands: 
    - agent.name -equals self-hosted
    #vmImage: windows-latest
  steps:
  - checkout: self
    submodules: true
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 8.x
    inputs:
      version: 8.x
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'src/nupkg_release'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  # - task: NuGetCommand@2
  #   inputs:
  #   command: 'push'
  #   packagesToPush: 'src/nupkg_release/*.nupkg'
  #   nuGetFeedType: 'external'
  #   publishFeedCredentials: 'DotNetBrightener Nuget'
  # - task: DotNetCoreCLI@2
  #   displayName: Push Nuget Package
  #   inputs:
  #     command: 'push'
  #     packagesToPush: 'nupkg_release/*.nupkg'
  #     nuGetFeedType: 'internal'
  #     publishVstsFeed: '034af936-b352-4b46-b58f-cb0cf6975259'