// <auto-generated />
using System;
using DotNetBrightener.Integration.DataMigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DotNetBrightener.Integration.DataMigration.Migrations.DataMigrationPostgreSQLDb
{
    [DbContext(typeof(DataMigrationPostgreSQLDbContext))]
    [Migration("20201203045133_InitializeDataMigrationSchema")]
    partial class InitializeDataMigrationSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DotNetBrightener.Integration.DataMigration.DataMigrationHistoryRecord", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("MigrationRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModuleId")
                        .HasColumnType("text");

                    b.HasKey("MigrationId");

                    b.ToTable("__DataMigrationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
