using System;
using System.Collections.Generic;

namespace DotNetBrightener.WebApi.GenericCRUD.Generator.SyntaxReceivers;

public interface IAutoGenerateDataServiceRegistration
{
    /// <summary>
    ///     Defines the entities that need to generate Data Service for.
    /// </summary>
    List<Type> Entities { get; }
}