// <auto-generated />
using System;
using DotNetBrightener.DataAccess.DataMigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetBrightener.DataAccess.DataMigration.PostgreSql.Migrations
{
    [DbContext(typeof(DataMigrationDbContext))]
    [Migration("20240502104503_Init_DataMigration_Schema")]
    partial class Init_DataMigration_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetBrightener.DataAccess.DataMigration.DataMigrationHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("AppliedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MigrationId");

                    b.ToTable("__DataMigrationsHistory", "DataMigration");
                });
#pragma warning restore 612, 618
        }
    }
}
